# Generated by Django 5.0.3 on 2024-03-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_company_website_remove_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
