# Generated by Django 5.0.3 on 2024-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
