# Generated by Django 5.0.3 on 2024-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_company_lat_company_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
